config/routes.rb
Birthday::Application.routes.draw do
  resources :bdays

end

app/models/bday.rb
class Bday < ActiveRecord::Base
  validates_format_of :my_date, :with => /^\d{1,2}\/\d{1,2}\/\d{4}$/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bdays_controller.rb
class BdaysController < ApplicationController
  # GET /bdays
  # GET /bdays.xml
  def index
    @bdays = Bday.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bdays }
    end
  end

  # GET /bdays/1
  # GET /bdays/1.xml
  def show
    @bday = Bday.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bday }
    end
  end

  # GET /bdays/new
  # GET /bdays/new.xml
  def new
    @bday = Bday.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bday }
    end
  end

  # GET /bdays/1/edit
  def edit
    @bday = Bday.find(params[:id])
  end

  # POST /bdays
  # POST /bdays.xml
  def create
    @bday = Bday.new(params[:bday])

    respond_to do |format|
      if @bday.save
        format.html { redirect_to(@bday, :notice => 'Bday was successfully created.') }
        format.xml  { render :xml => @bday, :status => :created, :location => @bday }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bday.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bdays/1
  # PUT /bdays/1.xml
  def update
    @bday = Bday.find(params[:id])

    respond_to do |format|
      if @bday.update_attributes(params[:bday])
        format.html { redirect_to(@bday, :notice => 'Bday was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bday.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bdays/1
  # DELETE /bdays/1.xml
  def destroy
    @bday = Bday.find(params[:id])
    @bday.destroy

    respond_to do |format|
      format.html { redirect_to(bdays_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bdays_helper.rb
module BdaysHelper
end

app/views/bdays/_form.html.erb
<%= form_for(@bday, :validate => true) do |f| %>
  <% if @bday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bday.errors.count, "error") %> prohibited this bday from being saved:</h2>

      <ul>
        <% @bday.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :my_date %>
    <br/>
    <%= f.text_field :my_date, :validate => true %>
  </div>
  <script type="text/javascript">
    $("#bday_my_date").datepicker({
      // UNCOMMENT these lines to fix the bug, and introduce unwanted functionality
//      beforeShow: function(dateText, inst) {
//        $(inst.input).focusout();
//      },
      onClose: function(dateText, inst) {
        $(inst.input).focusout();
      }
    });
  </script>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bdays/edit.html.erb
<h1>Editing bday</h1>

<%= render 'form' %>

<%= link_to 'Show', @bday %> |
<%= link_to 'Back', bdays_path %>

app/views/bdays/index.html.erb
<h1>Listing bdays</h1>

<table>
  <tr>
    <th>My date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bdays.each do |bday| %>
  <tr>
    <td><%= bday.my_date %></td>
    <td><%= link_to 'Show', bday %></td>
    <td><%= link_to 'Edit', edit_bday_path(bday) %></td>
    <td><%= link_to 'Destroy', bday, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bday', new_bday_path %>

app/views/bdays/new.html.erb
<h1>New bday</h1>

<%= render 'form' %>

<%= link_to 'Back', bdays_path %>

app/views/bdays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>My date:</b>
  <%= @bday.my_date %>
</p>


<%= link_to 'Edit', edit_bday_path(@bday) %> |
<%= link_to 'Back', bdays_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Birthday</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults, 'rails.validations' %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>